name: Run tests

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }}-${{ matrix.dependencies }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Don't cancel other jobs if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dependencies: ["latest", "old"]
        exclude:
          # There's no Python 3.7 on osx-latest, so exclude this combo
          - os: macos-latest
            dependencies: "old"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for git history (tags)

    - uses: prefix-dev/setup-pixi@v0.8.3
      with:
        environments: >-
          test-${{ matrix.dependencies }}
          test-xarray-${{ matrix.dependencies }}

    - name: Run basic tests
      run: |
        pixi run -e test-${{ matrix.dependencies }} basic-tests

    - name: Run xarray tests
      run: |
        pixi run -e test-xarray-${{ matrix.dependencies }} xarray-tests
